version: "3.7"

services:
    database: 
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: phonebook_db
            MYSQL_ROOT_PASSWORD: P123456p
            MYSQL_USER: clarusway
            MYSQL_PASSWORD: Clarusway_1
        command: --init-file /data/application/init.sql
        volumes:
          - ./init.sql:/data/application/init.sql
          - my-db:/var/lib/mysql
        networks:
            - clarusnet
    my-app:
        image: 331210975209.dkr.ecr.us-east-1.amazonaws.com/mucahit-k/phonebook-app:latest
        restart: always
        depends_on:
            - database
        deploy:
          mode: global 
        ports:
            - "80:80"
        networks:
            - clarusnet
volumes:
  my-db:
networks:
    clarusnet:
        driver: overlay